### PR TITLE
26 add new functionality for viewing and updating student in students

### PR DESCRIPTION
**Pull request by muhammad-mousa**
## Any student from the grid is editable and the changes are visible in the main grid without page reload
image

## Dialog
image

## Aftab Sattar is updated to Zeeshan (Updated)
image

### CODE REVIEW

**Comment by ZU3AIRE** [comment]
Can you make the dialog a bit smaller?
@muhammad-mousa

**Comment by muhammad-mousa** [comment]
Sure.

**Comment by muhammad-mousa** [comment]
@ZU3AIRE 
Is it ok or need further changes please let me know.
image

**Comment by ZU3AIRE** [comment]
For now it would be great ...

**Comment by ZU3AIRE** [comment]
Copy Id doesn't copies the correct students Id
image

**Comment by ZU3AIRE** [comment]
The rest of the things are working fine, so approving PRs

**Review by ZU3AIRE — APPROVED** [review]

**Pull request merged**
