### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by muhammad-mousa**
Update ReadMe file:
write steps to give the review.

### CODE REVIEW

**Comment by ZU3AIRE** [comment]
@muhammad-mousa I've updated the issue #4, please update the PR accordingly 😊

**Comment by muhammad-mousa** [comment]
Ok, I will update the PR accordingly and will let you know.

**Comment by muhammad-mousa** [comment]
@ZU3AIRE, I have updated the ReadMe File, have a look at this.

**Review by ZU3AIRE — APPROVED** [review]
We will update this Readme file in future after deployment on Vercel ...

**Pull request merged**
